### ISSUE TITLE
readme is for wusses

### ISSUE THREAD

**Issue by illustris** [krishh-konar/awesome-wm-shortcuts#1]
With reference to a669861ce06d0201e74ca0292bbe22c81244afbb,
adding documentation takes away from the low-effort slapped together feel of the codebase. Please revert these changes and force people to read the code to figure out what it does.

**Comment by krishh-konar** [comment]
Can't disagree on that, but it's more for reminding me what to do as I tend to forget things.
Closing this issue :stuck_out_tongue:
